- hosts: all
  remote_user: root
  gather_facts: no

# Generate random password for new_user_name and the new_user_name
# is required to change his/her password on first logon. 
# --extra-vars "uusername=kelvin upassword=testing"

  tasks:
    - name: create user with provided details
      user:
        name: "{{ uusername }}"
        password: "{{ upassword | password_hash('sha512') }}"
        groups: sudo
        state: present
        shell: "/bin/bash"
        system: no
        createhome: yes
        home: "/home/{{ uusername }}"
      when: uusername is defined
      register: user_created

    - name: Force user to change password
      shell: chage -d 0 {{ uusername }}
      when: user_created.changed

    - debug: msg="Password for {{ uusername }} is {{ upassword }}"
      when: user_created.changed
